apiVersion: apps/v1
kind: Deployment
metadata:
  name: angularweb
spec:
  selector:
    matchLabels:
      app: angularweb
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: angularweb
    spec:
      containers:
      - name: angularwebcont
        image: mransack/angularapp:v1
